# /etc/toolchain -- THE MACHINE BUILDS AND RUNS A PROGRAM WITH ITS OWN TOOLCHAIN.
#
# The closing claim of task C9 (cmd/TODO.md), and the one assertion in this tree that no
# b6sim test can make.  Grafted onto a copy of the image by run-toolchain.sh, not shipped
# on it.  filters.sh is the model, and its standing rule holds here too: WHAT MAY REACH THE
# LOG is names, diagnostics and numbers a program computed -- never a clock, a pid or a
# temporary's name.  cc names its temporaries /tmp/ccXXXXXX.s after the process id, so the
# only place one could appear is under -v, which this script does not use.
#
# WHAT IS UNDER TEST, and why none of it is reachable under the simulator:
#
#   * /usr/bin/cc's OWN SEARCH.  The driver looks for /usr/bin/cpp, /usr/bin/as and
#     /usr/bin/ld by absolute path.  Under b6sim those resolve on the BUILD MACHINE, which
#     is why cmd/cc/rootfs/test pins them with B6CPP/B6AS/B6LD instead -- and pinning them
#     is exactly what leaves the search itself unasserted.  Here nothing is pinned.
#   * /lib AND /usr/include, which task C9e put on the image for this and for nothing else.
#     The link below names no -L and no crt0.o: cc finds /lib/crt0.o, /lib/libc.a and
#     /lib/libruntime.a by itself, in that order, or the program does not link.
#   * THREE FORKS AND THREE EXECS through the real kernel, waited for one at a time with
#     the argument-less wait(2) this system has instead of waitpid().
#   * A PROGRAM THE MACHINE JUST BUILT, EXECUTED.  getxfile() reads an a.out that nothing
#     on the host ever touched.
#   * cc's temporaries in the image's own /tmp, made with mkstemps(3) -- and removed by the
#     atexit(3) handler lib/libc gained in the same task.  Section 4 asserts that /tmp is
#     empty afterwards, which is the only place either routine's cleanup is visible.
#
# hello.s IS GENERATED BY THE HOST and grafted in, because the one step of the chain this
# machine cannot take is the first: b6parse, b6lower and b6codegen belong to the external
# c-compiler repository.  So the fixture is the assembly of lib/test/hello.c as the host
# b6cc emitted it, and section 5 asserts that cc says so rather than reporting a missing
# file when it is handed the .c instead.  cmd/cc/README.md, "It cannot compile C".

echo toolchain begin >/tmp/toolchain.log

cd /tmp

# ---- 1. The whole chain in one command: as, then ld, with the standard link line.
cc -o hello hello.s
echo cc status $? >>/tmp/toolchain.log

# ---- 2. Run what it built.  This is the claim.
./hello >>/tmp/toolchain.log
echo hello status $? >>/tmp/toolchain.log

# ---- 3. Read it back with the machine's own binutils, which is task C9c's half of this.
#
# NO SEGMENT SIZE AND NO ADDRESS REACHES THIS LOG, on purpose.  Every number size(1) or
# nm(1) would print about this program is a property of crt0.o and libc.a rather than of
# hello.s, so a checked-in one would turn any edit to the C library into a failure of the
# toolchain test.  What is asserted here is that the tools RAN and found what is in the
# file; what the bytes are is asserted by run-toolchain.sh, which compares the whole a.out
# against the host build's afterwards and has nothing to check in at all.
size hello >/dev/null
echo size status $? >>/tmp/toolchain.log
nm hello | grep -c main >>/tmp/toolchain.log

# ---- 4. The stages separately, so that a failure names one of them.  The .o from `cc -c'
# and the one the run above made in /tmp and threw away are the same object, and a relink
# of it must reproduce the image byte for byte -- which is this script's own answer to the
# paragraph above: an identity, not a number.
cc -c hello.s
echo cc -c status $? >>/tmp/toolchain.log
cc -o hello2 hello.o
cmp hello hello2
echo relink identical $? >>/tmp/toolchain.log

# Nothing of cc's may survive it: every temporary is unlinked by the atexit(3) handler,
# whichever way the driver leaves.  The glob stands as written when it matches nothing,
# which is what an empty result looks like here.
echo /tmp/cc* >>/tmp/toolchain.log

# ---- 5. The preprocessor, with the image's own /usr/include on the search path -- and
# then the limitation, stated by the program rather than by a README.
echo '#include <sys/types.h>' >prep.c
echo 'daddr_t block;' >>prep.c
cc -E prep.c
grep -c daddr_t prep.i >>/tmp/toolchain.log
cc prep.c
echo cc on a .c status $? >>/tmp/toolchain.log

# hello is LEFT ON THE DISK, and it is the only thing this script does not clean up:
# run-toolchain.sh extracts it afterwards and compares it with what the host b6cc makes of
# the same hello.s, byte for byte.  That comparison is the closing claim of task C9 and it
# is the reason nothing above needs a checked-in number.
rm -f hello2 hello.o prep.c prep.i

# Last, as in session.sh and files.sh: there is no update daemon here, so nothing else
# flushes the cache.
sync
echo toolchain done >/dev/console
